export const metadata = {
  title: {
    default:'next.js toturial',
    template:'%s | barbodmsd'
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <header>header</header>
        {children}
        <footer>footer</footer>
      </body>
    </html>
  );
}
